export const COMIC_PREMISES: Record<string, string[]> = {
    'Ngôn tình': [
        "Tại sàn nhảy Club Audition, nữ chính là một 'Newbie' hậu đậu vô tình dẫm vào chân nam chính - một 'Vip' lạnh lùng. Thay vì tức giận, anh ta thách cô nhảy đôi.",
        "Chàng trai và cô gái là cặp đôi nhảy ăn ý nhất server nhưng chưa bao giờ gặp mặt. Ngày Offline hội quán, họ lướt qua nhau mà không biết, chỉ để lại một ánh mắt quen thuộc.",
        "Nữ chính thầm thích nam chính, mỗi ngày đều vào phòng nhảy của anh để spectate (xem). Một ngày nọ, anh bất ngờ mời cô vào nhảy cùng.",
        "Câu chuyện về một cặp đôi đã chia tay trong game (Ly hôn) nhưng ngoài đời thực lại vô tình trở thành đồng nghiệp chung công ty.",
        "Cô gái là chủ Fam lớn, chàng trai là một game thủ solo lang thang. Anh gia nhập Fam của cô chỉ để bảo vệ cô khỏi những lời đàm tiếu.",
        "Chàng trai luôn mặc đồ 'Mặc định' bị mọi người chê cười, nhưng thực ra anh là top 1 server đang dùng acc phụ để tìm tình yêu đích thực không màng vật chất.",
        "Trong một ván nhảy đôi, cả hai cùng Perfect x10 liên tiếp. Khoảnh khắc đó khiến họ cảm thấy như có thần giao cách cảm.",
        "Nam chính là DJ nổi tiếng của Club, nữ chính là cô gái bán hoa thường ghé qua. Anh sáng tác riêng một bản nhạc nhảy dành tặng cô.",
        "Hai người là oan gia ngõ hẹp, cứ gặp nhau trong phòng nhảy là cãi nhau. Nhưng khi một người vắng mặt, người kia lại thấy trống trải.",
        "Cô gái bị người yêu trong game lừa dối (đào mỏ). Chàng trai xuất hiện như một vị cứu tinh, tặng cô bộ cánh đẹp nhất Shop và giúp cô lấy lại tự tin.",
        "Mối tình chị-em: Chàng trai kém tuổi quyết tâm luyện tập để thắng cô gái trong chế độ Beat Up, với phần thưởng là một buổi hẹn hò.",
        "Câu chuyện tình yêu bắt đầu từ một lời thách đấu: 'Nếu anh thắng ván này, em phải làm Couple của anh'.",
        "Nữ chính là NPC hướng dẫn tân thủ, nam chính là người chơi đầu tiên phải lòng một NPC.",
        "Họ yêu nhau qua mạng 3 năm. Ngày quyết định gặp mặt, cả hai đều lo sợ đối phương thất vọng về ngoại hình thật của mình.",
        "Nam chính là idol nổi tiếng, trốn vào game để tìm sự bình yên. Anh gặp nữ chính, người duy nhất đối xử với anh như người bình thường.",
        "Vào ngày lễ tình nhân, cô gái đứng một mình ở Wedding Hall. Chàng trai bước vào và quỳ xuống: 'Anh đến muộn, xin lỗi em'.",
        "Cô gái luôn nhảy Miss, chàng trai luôn nhảy Perfect. Anh kiên nhẫn dạy cô từng nhịp, tình cảm dần nảy sinh qua những phím bấm.",
        "Cả hai cùng tranh giành một món đồ Limited trong Shop. Cuối cùng họ quyết định mua đồ đôi.",
        "Nam chính giả gái để trêu chọc mọi người, nhưng lại vô tình khiến nữ chính rung động. Anh phải làm sao để thú nhận?",
        "Sau 10 năm server đóng cửa, họ gặp lại nhau trong phiên bản Audition Mobile, nhận ra nick name cũ của nhau."
    ],
    'Hài hước': [
        "Hai nhân vật thi đấu nhảy nhưng mạng lag, khiến nhân vật của họ thực hiện những động tác kỳ quặc không đỡ nổi.",
        "Nam chính muốn tỏ tình lãng mạn bằng cách nhảy bài 'Aloha' nhưng lại quên mua nhẫn, lúc quỳ xuống thì lôi ra... một quả chuối.",
        "Cuộc chiến giữa hai Fam lớn chỉ vì tranh giành xem ai mặc bộ đồ 'bò sữa' đẹp hơn.",
        "Nữ chính trang điểm lộng lẫy đi hẹn hò online, nhưng filter bị lỗi khiến mặt cô biến thành mặt troll.",
        "Chàng trai cố gắng thể hiện kỹ năng 'nhảy 8k' nhưng ngón tay bị chuột rút, gõ loạn xạ ra tin nhắn tỏ tình nhầm người.",
        "Một nhóm bạn rủ nhau cosplay nhân vật Audition ngoài đời thực và đi nhầm vào một đám cưới thật.",
        "Nhân vật nam quên mặc quần khi tham gia lễ thành hôn trong game.",
        "Cuộc thi 'Ai nhảy xấu nhất' được tổ chức, và người thắng cuộc lại là người nhảy nghiêm túc nhất.",
        "Nam chính dùng tool hack để auto Perfect, nhưng tool lỗi khiến nhân vật chỉ biết quay vòng tròn chóng mặt.",
        "Hai người bạn thân cùng tán tỉnh một cô gái trong game, phát hiện ra đó là... thằng bạn thân thứ 3 giả gái.",
        "Sự cố hy hữu: Vừa nhảy vừa ăn mì tôm, nam chính làm đổ mì lên bàn phím và nhân vật tự động nhảy điệu 'co giật'.",
        "Nữ chính mua nhầm tóc của nam và nam chính mua nhầm váy của nữ. Họ quyết định mặc luôn để tạo trend mới.",
        "Đang nhảy hăng say thì mẹ gank (bắt gặp), nam chính phải giả vờ đang học bài trực tuyến với tư thế kỳ quặc.",
        "Chàng trai muốn tặng quà cho bạn gái nhưng ấn nhầm nút 'Xóa nhân vật'.",
        "Hội những người chơi Audition bằng chân tổ chức giải đấu.",
        "Nữ chính vào nhầm phòng Boss Battle, bị Boss rượt chạy tóe khói thay vì nhảy.",
        "Cuộc đối đầu giữa 'Thánh Cào Phím' và 'Chúa Tể Lag', trận đấu diễn ra trong im lặng vì cả hai đều bị disconnect.",
        "Nam chính tỏ tình bằng cách xếp chữ bằng nhân vật, nhưng mọi người lại nhìn ra chữ... 'Đồ ngốc'.",
        "Nhân vật bị kẹt trong tư thế Finish Move lơ lửng trên không suốt 3 tiếng đồng hồ.",
        "Đám cưới trong game bị phá đám bởi một đàn NPC zombie đi lạc vào."
    ],
    'Kinh dị': [
        "Phòng nhảy số 404 luôn sáng đèn lúc 3 giờ sáng, nhưng không ai tạo ra nó. Người vào đó sẽ thấy nhân vật của mình tự di chuyển.",
        "Một bản nhạc bí ẩn xuất hiện trong danh sách, ai chọn nó sẽ bị 'disconnect' khỏi cuộc đời thực.",
        "Cô gái nhìn thấy một nhân vật đứng ở góc phòng nhảy, mặc bộ đồ giống hệt mình, nhưng mặt không có ngũ quan.",
        "Tin nhắn từ một người bạn đã mất 1 năm trước bỗng hiện lên: 'Vào room nhanh lên, tớ đang đợi'.",
        "Nhân vật trong game bỗng quay đầu lại nhìn thẳng vào màn hình và mỉm cười quỷ dị.",
        "Mỗi lần nhảy Perfect, một giọt máu lại xuất hiện trên màn hình.",
        "Cặp đôi nhảy trong Wedding Hall phát hiện ra trọng tài là một bóng ma không chân.",
        "Người chơi phát hiện ra bóng của nhân vật trong game di chuyển không khớp với hành động.",
        "Một bộ trang phục bị nguyền rủa: Ai mặc vào sẽ không thể thoát game.",
        "Âm thanh tiếng cười khúc khích phát ra từ loa dù đã tắt tiếng game.",
        "NPC bán đồ trong Shop thay đổi khuôn mặt giận dữ khi bạn không mua gì.",
        "Phòng nhảy 'Địa Ngục': Nơi người thua cuộc sẽ bị mất đi một ký ức.",
        "Bạn nhảy của nam chính cứ liên tục chat những dòng mã nhị phân vô nghĩa, giải mã ra là tọa độ nhà anh ta.",
        "Chiếc gương trong phòng chờ phản chiếu một thế giới khác, nơi các nhân vật đang gào thét.",
        "Sau khi bảo trì, server xuất hiện thêm một Map lạ: Nghĩa địa hoang vắng.",
        "Lời nguyền Finish Move: Ai thực hiện thành công sẽ biến mất.",
        "Một tài khoản lạ tên 'Unknown' luôn join vào phòng dù có đặt mật khẩu.",
        "Cô gái phát hiện ra avatar của mình đang già đi mỗi ngày.",
        "Tiếng gõ phím vang lên trong phòng trống dù bạn đang không chạm vào bàn phím.",
        "Trò chơi tự động bật lên giữa đêm và phát bài nhạc đám ma."
    ],
    'Hành động': [
        "Thế giới Audition thực chất là một đấu trường ảo, nơi các vũ công chiến đấu bằng nhịp điệu để giành quyền kiểm soát thành phố.",
        "Nam chính là điệp viên ngầm, sử dụng các bước nhảy để truyền mã bí mật cho tổ chức.",
        "Cuộc đua xe kết hợp nhảy Audition: Vừa lái xe tốc độ cao vừa phải Perfect để tăng tốc.",
        "Các nhân vật Audition có khả năng triệu hồi vũ khí từ các nốt nhạc.",
        "Đại chiến giữa hai phe: Phe truyền thống (4k) và Phe hiện đại (8k) để tranh giành lãnh thổ.",
        "Nữ chính bị bắt cóc vào thế giới game, cô phải thắng trùm cuối bằng kỹ năng nhảy để thoát ra.",
        "Hệ thống Audition bị virus xâm nhập, biến các NPC thành quái vật. Các vũ công hợp sức chiến đấu.",
        "Giải đấu tử thần: Người thua cuộc sẽ bị xóa acc vĩnh viễn.",
        "Nam chính sở hữu đôi giày thần tốc, mỗi bước nhảy tạo ra sóng xung kích.",
        "Vũ công đường phố sử dụng Parkour kết hợp nhảy để trốn thoát cảnh sát ảo.",
        "Cuộc chiến giành viên 'Đá Nhịp Điệu' có khả năng thay đổi thực tại.",
        "Hacker tấn công server, nam chính phải 'nhảy' qua các bức tường lửa để cứu dữ liệu.",
        "Các Fam biến thành các băng đảng xã hội đen, tranh giành địa bàn bằng các trận Dance Battle đẫm máu.",
        "Nhân vật chính phát hiện mình là một AI có ý thức, chiến đấu chống lại sự kiểm soát của Admin.",
        "Sàn nhảy biến thành sàn đấu boxing, mỗi nhịp Beat là một cú đấm.",
        "Nhiệm vụ giải cứu công chúa (Admin) bị nhốt trong tòa tháp Beat Up.",
        "Cuộc rượt đuổi trên tàu cao tốc, nhảy để tránh chướng ngại vật.",
        "Nam chính là vệ sĩ, dùng điệu nhảy để tạo lá chắn bảo vệ thân chủ.",
        "Thế giới hậu tận thế, năng lượng duy nhất còn lại đến từ những bước nhảy Perfect.",
        "Trận chiến cuối cùng trên đỉnh tháp truyền hình, người thắng sẽ trở thành Chúa tể Giai điệu."
    ],
    'Đời thường': [
        "Một ngày bình thường của chủ quán Net: Chứng kiến đủ loại hỉ nộ ái ố của game thủ Audition.",
        "Nhóm bạn thân cấp 3 cùng nhau lập Fam, chia sẻ những câu chuyện học tập và cuộc sống qua game.",
        "Chàng nhân viên văn phòng xả stress bằng cách 'quẩy' Audition mỗi tối sau giờ làm.",
        "Câu chuyện về một người mẹ đơn thân tìm lại niềm vui tuổi trẻ qua game nhảy.",
        "Hai người hàng xóm ồn ào phát hiện ra họ là bạn nhảy ăn ý của nhau trong game.",
        "Hành trình tiết kiệm tiền ăn sáng của cô sinh viên nghèo để mua bộ cánh mơ ước trong game.",
        "Chàng trai dạy bà của mình chơi Audition để bà đỡ buồn.",
        "Tình bạn xuyên biên giới giữa một du học sinh và người bạn ở quê nhà qua những ván nhảy.",
        "Buổi Offline Fam đầy cảm xúc, nơi những người bạn ảo lần đầu gặp mặt.",
        "Cô gái nhút nhát tìm thấy sự tự tin khi hóa thân thành nhân vật sành điệu trong game.",
        "Chuyện tình tay ba rắc rối giữa những người bạn cùng lớp chơi chung một tiệm Net.",
        "Nam chính cố gắng cân bằng giữa việc học thi đại học và đam mê leo top server.",
        "Hai chị em gái tranh giành máy tính để chơi Audition mỗi tối.",
        "Kỷ niệm về quán Net cỏ ngày xưa, với những bàn phím mờ chữ và tiếng đập phím 'cạch cạch'.",
        "Chàng trai thất nghiệp tìm thấy cơ hội việc làm nhờ mối quan hệ trong game.",
        "Câu chuyện về sự trưởng thành: Từ một 'trẻ trâu' phá game thành một Fam chủ mẫu mực.",
        "Một ngày chủ nhật lười biếng, chỉ nằm nhà nghe nhạc game và chat chit.",
        "Nỗi buồn khi server bảo trì, cả nhóm không biết làm gì.",
        "Niềm vui vỡ òa khi quay được món đồ hiếm từ vòng quay may mắn.",
        "Bức thư chia tay gửi lại cho người bạn game trước khi đi du học."
    ],
    'Học đường': [
        "Nữ sinh mới chuyển trường bị bắt nạt, nhưng trong game cô là 'Chị Đại' được mọi người kính nể.",
        "Hội học sinh tổ chức giải đấu Audition toàn trường thay vì hội thao.",
        "Thầy giáo chủ nhiệm hóa ra là cao thủ Audition ẩn danh.",
        "Câu lạc bộ Audition của trường có nguy cơ bị giải thể nếu không thắng giải đấu quận.",
        "Mối tình gà bông giữa chàng hotboy và cô nàng mọt sách bắt đầu từ phòng nhảy.",
        "Nam chính lén chơi game trong giờ tin học và bị cô giáo bắt gặp, bị phạt nhảy mẫu cho cả lớp xem.",
        "Cuộc đối đầu giữa đội cổ vũ và đội game thủ trong trường.",
        "Bí mật của hoa khôi trường: Là một 'nghiện' game chính hiệu.",
        "Bài tập về nhà: Phân tích nhịp điệu của bài nhạc trong game.",
        "Cả lớp đoàn kết cày level cho acc của lớp trưởng bị hack.",
        "Lời đồn về phòng máy tính cũ trong trường, nơi có thể đăng nhập vào server bí mật.",
        "Chàng trai nhút nhát dùng game để tiếp cận crush cùng lớp.",
        "Cuộc thi Talent Show: Nhóm bạn biểu diễn nhảy mô phỏng nhân vật Audition.",
        "Học sinh cá biệt và lớp trưởng gương mẫu tìm thấy tiếng nói chung qua game.",
        "Scandal tình ái trong trường bắt nguồn từ việc ghép đôi trong game.",
        "Buổi lễ tốt nghiệp, cả lớp cùng nhảy điệu nhảy Audition để kỷ niệm.",
        "Thư tình được giấu trong phần tin nhắn của game.",
        "Cuộc chiến giành máy tính xịn nhất trong phòng tin học.",
        "Nam chính bị cấm chơi game, phải lén lút trốn học đi chơi.",
        "Tình bạn tan vỡ vì hiểu lầm trong game và hành trình hàn gắn."
    ],
    'Xuyên không': [
        "Đang nhảy Finish Move, nữ chính bị hút vào màn hình và trở thành nhân vật của mình trong thế giới Audition.",
        "Nam chính xuyên không về quá khứ năm 2006, thời điểm Audition mới ra mắt, và trở thành huyền thoại.",
        "Nhân vật game Audition xuyên không ra ngoài đời thực, gây ra bao tình huống dở khóc dở cười.",
        "Cả một Fam bị đưa đến thế giới phép thuật, nơi họ phải dùng kỹ năng nhảy để thi triển phép thuật.",
        "Nữ chính xuyên vào cuốn tiểu thuyết, nhưng hệ thống sức mạnh lại là giao diện Audition.",
        "Nam chính tỉnh dậy thấy mình là NPC bán quần áo trong Shop.",
        "Xuyên không đến tương lai, nơi Audition là môn thể thao Olympic.",
        "Cô gái lạc vào thế giới đảo ngược: Nơi mọi người di chuyển bằng cách nhảy theo nhịp.",
        "Chàng trai phải hoàn thành nhiệm vụ 'Lên nhẫn' với công chúa vương quốc ảo để được về nhà.",
        "Thế giới nơi đẳng cấp xã hội được quyết định bởi Level trong game.",
        "Nữ chính trở thành DJ của thế giới ảo, nắm giữ quyền năng điều khiển cảm xúc mọi người qua nhạc.",
        "Xuyên không vào server của nước khác, bất đồng ngôn ngữ nhưng kết nối bằng âm nhạc.",
        "Nam chính bị kẹt trong vòng lặp thời gian của một bài hát, phải Perfect 100% mới thoát ra được.",
        "Các nhân vật lịch sử nổi tiếng xuyên không đến hiện đại và nghiện chơi Audition.",
        "Cuộc phiêu lưu tìm đường về nhà qua các sàn nhảy (Map) khác nhau.",
        "Nữ chính phải đấu nhảy với Ma Vương để cứu thế giới.",
        "Xuyên vào thân xác của một noob (người chơi gà), nam chính phải cày lại từ đầu.",
        "Thế giới nơi tiền tệ là Den và Vcoin.",
        "Nam chính mang theo kho nhạc hiện đại về quá khứ, làm chao đảo thế giới Audition cổ điển.",
        "Cuộc gặp gỡ giữa người chơi xuyên không và AI bản địa có cảm xúc."
    ]
};
