
import { CosmeticItem } from '../types';

export const AVATAR_FRAMES: CosmeticItem[] = [
    {
        id: 'default',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.default',
        rarity: 'common',
        cssClass: 'frame-none',
    },
    {
        id: 'wood-basic',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.wood',
        rarity: 'common',
        cssClass: 'frame-wood',
        unlockCondition: { level: 2 },
    },
    {
        id: 'neon-blue',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.neonBlue',
        rarity: 'rare',
        cssClass: 'frame-basic-blue',
        unlockCondition: { level: 5 },
    },
    {
        id: 'neon-pink',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.neonPink',
        rarity: 'rare',
        cssClass: 'frame-basic-pink',
        unlockCondition: { level: 10 },
    },
    {
        id: 'musical-note',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.music',
        rarity: 'rare',
        cssClass: 'frame-music',
        unlockCondition: { level: 15 },
    },
    {
        id: 'gradient-spin',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.gradientSpin',
        rarity: 'epic',
        cssClass: 'frame-gradient-spin',
        unlockCondition: { level: 20 },
    },
    {
        id: 'sakura-bloom',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.sakura',
        rarity: 'epic',
        cssClass: 'frame-sakura',
        unlockCondition: { level: 25 },
    },
    {
        id: 'cyber-tech',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.cyber',
        rarity: 'epic',
        cssClass: 'frame-cyber',
        unlockCondition: { level: 30 },
    },
    {
        id: 'angel-wings',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.angel',
        rarity: 'legendary',
        cssClass: 'frame-angel',
        unlockCondition: { level: 35 },
    },
    {
        id: 'demon-aura',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.demon',
        rarity: 'legendary',
        cssClass: 'frame-demon',
        unlockCondition: { level: 40 },
    },
    {
        id: 'thunder-storm',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.thunder',
        rarity: 'legendary',
        cssClass: 'frame-thunder',
        unlockCondition: { level: 45 },
    },
    {
        id: 'legendary-gold',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.legendaryGold',
        rarity: 'legendary',
        cssClass: 'frame-legendary-gold',
        unlockCondition: { level: 50 },
    },
    {
        id: 'ice-crystal',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.ice',
        rarity: 'legendary',
        cssClass: 'frame-ice',
        unlockCondition: { level: 55 },
    },
    {
        id: 'love-beat',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.love',
        rarity: 'epic',
        cssClass: 'frame-love',
        unlockCondition: { level: 60 },
    },
    {
        id: 'galaxy-void',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.galaxy',
        rarity: 'mythic',
        cssClass: 'frame-galaxy',
        unlockCondition: { level: 70 },
    },
    {
        id: 'matrix-code',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.matrix',
        rarity: 'mythic',
        cssClass: 'frame-matrix',
        unlockCondition: { level: 80 },
    },
    {
        id: 'rainbow-glitch',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.glitch',
        rarity: 'mythic',
        cssClass: 'frame-rainbow-glitch',
        unlockCondition: { level: 90 },
    },
    {
        id: 'mythic-fire',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.mythicFire',
        rarity: 'mythic',
        cssClass: 'frame-mythic-fire',
        unlockCondition: { level: 100 },
    },
    {
        id: 'infinity-god',
        type: 'frame',
        nameKey: 'creator.cosmetics.frames.god',
        rarity: 'mythic',
        cssClass: 'frame-infinity',
        unlockCondition: { level: 120 },
    }
];

export const ACHIEVEMENT_TITLES: CosmeticItem[] = [
    {
        id: 'newbie',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.newbie',
        rarity: 'common',
        cssClass: 'title-basic',
    },
    {
        id: 'dancer',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.dancer',
        rarity: 'common',
        cssClass: 'title-basic',
        unlockCondition: { level: 2 },
    },
    {
        id: 'style-icon',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.styleIcon',
        rarity: 'rare',
        cssClass: 'title-neon-blue',
        unlockCondition: { level: 5 },
    },
    {
        id: 'party-animal',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.party',
        rarity: 'rare',
        cssClass: 'title-neon-pink',
        unlockCondition: { level: 10 },
    },
    {
        id: 'rhythm-master',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.rhythm',
        rarity: 'rare',
        cssClass: 'title-music',
        unlockCondition: { level: 15 },
    },
    {
        id: 'vip',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.vip',
        rarity: 'epic',
        cssClass: 'title-vip-gold',
        unlockCondition: { level: 20 },
    },
    {
        id: 'charming',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.charming',
        rarity: 'epic',
        cssClass: 'title-sakura',
        unlockCondition: { level: 25 },
    },
    {
        id: 'cyber-punk',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.cyber',
        rarity: 'epic',
        cssClass: 'title-cyber',
        unlockCondition: { level: 30 },
    },
    {
        id: 'angel-voice',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.angel',
        rarity: 'legendary',
        cssClass: 'title-angel',
        unlockCondition: { level: 35 },
    },
    {
        id: 'demon-king',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.demon',
        rarity: 'legendary',
        cssClass: 'title-demon',
        unlockCondition: { level: 40 },
    },
     {
        id: 'thunder-lord',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.thunder',
        rarity: 'legendary',
        cssClass: 'title-thunder',
        unlockCondition: { level: 45 },
    },
    {
        id: 'glitch-master',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.glitchMaster',
        rarity: 'legendary',
        cssClass: 'title-cyber-glitch',
        unlockCondition: { level: 50 },
    },
     {
        id: 'ice-queen',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.ice',
        rarity: 'legendary',
        cssClass: 'title-ice',
        unlockCondition: { level: 55 },
    },
     {
        id: 'heart-breaker',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.love',
        rarity: 'epic',
        cssClass: 'title-love',
        unlockCondition: { level: 60 },
    },
    {
        id: 'galaxy-star',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.galaxy',
        rarity: 'mythic',
        cssClass: 'title-galaxy',
        unlockCondition: { level: 70 },
    },
    {
        id: 'the-one',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.matrix',
        rarity: 'mythic',
        cssClass: 'title-matrix',
        unlockCondition: { level: 80 },
    },
     {
        id: 'legend',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.legend',
        rarity: 'mythic',
        cssClass: 'title-rainbow',
        unlockCondition: { level: 90 },
    },
    {
        id: 'audition-god',
        type: 'title',
        nameKey: 'creator.cosmetics.titles.auditionGod',
        rarity: 'mythic',
        cssClass: 'title-mythic-fire',
        unlockCondition: { level: 100 },
    }
];

export const ALL_COSMETICS = [...AVATAR_FRAMES, ...ACHIEVEMENT_TITLES];

export const getCosmeticById = (id: string | undefined, type: 'frame' | 'title'): CosmeticItem | undefined => {
    const list = type === 'frame' ? AVATAR_FRAMES : ACHIEVEMENT_TITLES;
    return list.find(item => item.id === id) || list[0]; // Default to first item
};
