import React, { useEffect, useMemo, useState } from 'react';
import { Icons } from '../components/Icons';
import { useNotification } from '../components/NotificationSystem';
import { createDanceVideoOrder, getDanceVideoTemplates } from '../services/danceVideoService';
import { uploadFileToR2 } from '../services/storageService';
import type { DanceVideoTemplate } from '../types';

const STATUS_COPY = ['1. Thanh toán Vcoin', '2. Tải ảnh nhân vật', '3. Xác nhận & chờ xử lý'];
export const DanceVideoOrders: React.FC = () => {
  const { notify } = useNotification();
  const [templates, setTemplates] = useState<DanceVideoTemplate[]>([]);
  const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<DanceVideoTemplate | null>(null); const [step, setStep] = useState(1);
  const [files, setFiles] = useState<File[]>([]); const [name, setName] = useState(''); const [zalo, setZalo] = useState(''); const [note, setNote] = useState(''); const [submitting, setSubmitting] = useState(false);
  const load = async () => { setLoading(true); try { setTemplates(await getDanceVideoTemplates()); } catch (e: any) { notify(e.message || 'Không thể tải video mẫu.', 'error'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => templates.filter((item) => `${item.title} ${item.description} ${item.category}`.toLowerCase().includes(search.toLowerCase())), [templates, search]);
  const openOrder = (template: DanceVideoTemplate) => { setSelected(template); setStep(1); setFiles([]); };
  const submit = async () => {
    if (!selected || files.length !== selected.required_image_count) return;
    setSubmitting(true);
    try {
      const urls = await Promise.all(files.map((file, index) => uploadFileToR2(file, `dance-orders/${selected.id}/character-${index + 1}`)));
      await createDanceVideoOrder({ templateId: selected.id, characterImageUrls: urls, customerName: name, contactZalo: zalo, note });
      notify('Đặt video thành công. Job đã được ghim ở đầu Lịch sử tạo.', 'success'); setSelected(null); window.location.assign('/gallery');
    } catch (e: any) { notify(e.message?.includes('INSUFFICIENT_VCOIN') ? 'Số dư Vcoin không đủ. Vui lòng nạp thêm.' : (e.message || 'Không thể tạo đơn.'), 'error'); } finally { setSubmitting(false); }
  };
  return <div className="space-y-6 pb-24 animate-fade-in">
    <section className="neu-card overflow-hidden border border-fuchsia-500/30 bg-gradient-to-r from-[#160b25] via-[#11152c] to-[#071d27] p-6 sm:p-9">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-2xl"><span className="inline-flex items-center gap-2 rounded-full border border-fuchsia-400/30 bg-black/20 px-3 py-1 text-[11px] font-black uppercase tracking-widest text-fuchsia-300"><Icons.Video className="h-4 w-4" /> Motion Control Studio</span><h1 className="mt-3 font-accent text-3xl font-black text-white sm:text-4xl">Đặt Làm Video AI</h1><p className="mt-2 text-sm leading-relaxed text-slate-300">Chọn video Dance AI mẫu, gửi ảnh nhân vật game và nhận video copy đúng chuyển động mẫu. Xử lý nhanh từ 15–30 phút, tối đa 24 giờ.</p></div><div className="rounded-2xl border border-amber-400/30 bg-amber-400/10 px-4 py-3 text-xs font-bold text-amber-100"><b className="block text-amber-300">Chỉ làm theo video mẫu</b>Không nhận copy video ngoài thư viện.</div></div>
    </section>
    <section className="neu-card p-4 sm:p-5"><label className="relative block"><Icons.Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-fuchsia-400" /><input className="neu-input h-14 w-full rounded-2xl pl-12 pr-4 text-base font-bold" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Tìm dance, concept hoặc phong cách..." /></label></section>
    {loading ? <div className="neu-card flex min-h-64 items-center justify-center"><Icons.Loader className="h-8 w-8 animate-spin text-fuchsia-500" /></div> : visible.length === 0 ? <div className="neu-card p-12 text-center text-sm text-slate-400">Chưa có video mẫu phù hợp. Admin có thể thêm mẫu trong Quản trị Admin.</div> : <section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{visible.map((item) => <article key={item.id} className="neu-card group overflow-hidden p-3"><div className="relative aspect-video overflow-hidden rounded-2xl bg-black"><video src={item.preview_video_url} poster={item.thumbnail_url} className="h-full w-full object-cover" muted playsInline preload="metadata" controls /><span className="absolute left-3 top-3 rounded-full bg-black/70 px-2 py-1 text-[10px] font-black text-white">{item.category || 'Dance AI'}</span></div><div className="p-2 pt-4"><h2 className="font-accent text-base font-black text-slate-900 dark:text-white">{item.title}</h2><p className="mt-1 min-h-10 text-xs leading-relaxed text-slate-500 dark:text-slate-300">{item.description || 'Video copy chuyển động Motion Control.'}</p><div className="mt-4 flex items-center justify-between"><span className="inline-flex items-center gap-1 text-sm font-black text-amber-500"><Icons.Gem className="h-4 w-4" />{item.price_vcoin.toLocaleString()} Vcoin</span><button onClick={() => openOrder(item)} className="neu-button-primary inline-flex min-h-11 items-center gap-2 rounded-xl px-4 text-xs font-black"><Icons.Video className="h-4 w-4" />Đặt làm video</button></div></div></article>)}</section>}
    {selected && <div className="fixed inset-0 z-[100] flex items-end bg-black/65 p-0 backdrop-blur-sm sm:items-center sm:justify-center sm:p-5"><section role="dialog" aria-modal="true" className="max-h-[92dvh] w-full max-w-2xl overflow-y-auto rounded-t-[2rem] border border-white/15 bg-[#101221] p-5 shadow-2xl sm:rounded-[2rem] sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-widest text-fuchsia-400">Đặt theo mẫu đã chọn</p><h2 className="mt-1 text-xl font-black text-white">{selected.title}</h2></div><button aria-label="Đóng" onClick={() => setSelected(null)} className="neu-button flex h-11 w-11 items-center justify-center rounded-xl"><Icons.X className="h-5 w-5" /></button></div><div className="mt-6 grid grid-cols-3 gap-2">{STATUS_COPY.map((label, index) => <div key={label} className={`rounded-xl p-3 text-center text-[11px] font-bold ${step === index + 1 ? 'bg-fuchsia-500 text-white' : 'bg-white/5 text-slate-400'}`}>{label}</div>)}</div>
      {step === 1 && <div className="mt-6 space-y-4"><div className="rounded-2xl border border-amber-400/30 bg-amber-400/10 p-4 text-sm leading-relaxed text-amber-50"><b>Thanh toán trước: {selected.price_vcoin.toLocaleString()} Vcoin.</b><br/>Khi xác nhận ở bước cuối, hệ thống trừ Vcoin trực tiếp. Đơn đã được admin tiếp nhận sẽ không hủy hoặc hoàn Vcoin.</div><button onClick={() => setStep(2)} className="neu-button-primary w-full rounded-2xl py-3.5 text-sm font-black">Tiếp tục tải ảnh nhân vật</button></div>}
      {step === 2 && <div className="mt-6 space-y-4"><div className="rounded-2xl border border-cyan-400/25 bg-cyan-400/10 p-4 text-xs leading-relaxed text-cyan-50">Cần <b>{selected.required_image_count} ảnh nhân vật</b> rõ nét{selected.required_image_count > 1 ? ', mỗi nhân vật một ảnh' : ''}. Ảnh tách nền càng tốt. Hãy mix sẵn trang phục mong muốn trong game.</div><label className="block cursor-pointer rounded-2xl border-2 border-dashed border-fuchsia-400/40 p-6 text-center"><Icons.Upload className="mx-auto h-7 w-7 text-fuchsia-400" /><b className="mt-2 block text-sm text-white">Chọn đúng {selected.required_image_count} ảnh nhân vật</b><small className="mt-1 block text-slate-400">PNG, JPG, WEBP · tải thẳng lên R2 bảo mật</small><input className="sr-only" type="file" accept="image/*" multiple={selected.required_image_count > 1} onChange={(e) => setFiles(Array.from(e.target.files || []).slice(0, selected.required_image_count))} /></label>{files.length > 0 && <p className={files.length === selected.required_image_count ? 'text-xs text-emerald-400' : 'text-xs text-amber-400'}>Đã chọn {files.length}/{selected.required_image_count} ảnh: {files.map((file) => file.name).join(', ')}</p>}<a className="block text-center text-xs font-bold text-fuchsia-300 underline" href="/support">Không biết chụp ảnh? Liên hệ Facebook / TikTok / Zalo Admin để được hỗ trợ.</a><div className="flex gap-3"><button onClick={() => setStep(1)} className="neu-button flex-1 rounded-2xl py-3 text-sm font-bold">Quay lại</button><button disabled={files.length !== selected.required_image_count} onClick={() => setStep(3)} className="neu-button-primary flex-1 rounded-2xl py-3 text-sm font-black disabled:opacity-40">Tiếp tục</button></div></div>}
      {step === 3 && <div className="mt-6 space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-300">Tên liên hệ<input className="neu-input mt-1 h-11 w-full rounded-xl px-3" value={name} onChange={(e) => setName(e.target.value)} placeholder="Không bắt buộc" /></label><label className="text-xs font-bold text-slate-300">Zalo để Admin liên hệ<input className="neu-input mt-1 h-11 w-full rounded-xl px-3" value={zalo} onChange={(e) => setZalo(e.target.value)} placeholder="Không bắt buộc" /></label></div><label className="block text-xs font-bold text-slate-300">Ghi chú yêu cầu<textarea className="neu-input mt-1 min-h-20 w-full rounded-xl p-3" value={note} onChange={(e) => setNote(e.target.value)} placeholder="Ví dụ: cần giao trước 20:00..." /></label><div className="rounded-2xl bg-white/5 p-4 text-xs leading-relaxed text-slate-300"><b className="text-white">Xác nhận:</b> Video sẽ làm giống mẫu “{selected.title}”, job xuất hiện ở đầu Lịch sử tạo với trạng thái “Đang chờ xử lý”.</div><div className="flex gap-3"><button onClick={() => setStep(2)} className="neu-button flex-1 rounded-2xl py-3 text-sm font-bold">Quay lại</button><button disabled={submitting} onClick={() => void submit()} className="neu-button-primary flex-1 rounded-2xl py-3 text-sm font-black disabled:opacity-50">{submitting ? 'Đang tạo job...' : `Xác nhận · trừ ${selected.price_vcoin} Vcoin`}</button></div></div>}
    </section></div>}
  </div>;
};
