import React, { useEffect, useMemo, useState } from 'react';
import { Icons } from '../components/Icons';
import { adminDanceVideoAction, getAdminDanceVideoData } from '../services/danceVideoService';
import { uploadFileToR2 } from '../services/storageService';
import './dance-video-admin.css';

type Tab = 'orders' | 'templates';
const freshTemplate = (position: number) => ({ title: '', category: 'Dance AI', description: '', preview_video_url: '', price_vcoin: 50, required_image_count: 1, is_active: true, display_order: position });

export const DanceVideoAdminWorkspace: React.FC = () => {
  const [tab, setTab] = useState<Tab>('orders'); const [templates, setTemplates] = useState<any[]>([]); const [jobs, setJobs] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(''); const [draft, setDraft] = useState<any | null>(null); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); try { const data = await getAdminDanceVideoData(); setTemplates(data.templates || []); setJobs(data.jobs || []); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const visibleJobs = useMemo(() => jobs.filter((job) => `${job.dance_video_templates?.title || ''} ${job.users?.display_name || ''} ${job.users?.email || ''} ${job.contact_zalo || ''}`.toLowerCase().includes(query.toLowerCase())), [jobs, query]);
  const counts = useMemo(() => ({ pending: jobs.filter((item) => item.status === 'pending').length, progress: jobs.filter((item) => item.status === 'processing').length, complete: jobs.filter((item) => item.status === 'completed').length }), [jobs]);
  const updateJob = async (job: any, patch: Record<string, unknown>) => { await adminDanceVideoAction({ action: 'update-job', id: job.id, status: patch.status || job.status, adminNote: patch.adminNote ?? job.admin_note, resultVideoUrl: patch.resultVideoUrl ?? job.result_video_url }); await load(); };
  const saveTemplate = async () => { if (!draft) return; setSaving(true); try { await adminDanceVideoAction({ action: 'save-template', template: { ...draft, price_vcoin: Number(draft.price_vcoin), required_image_count: Number(draft.required_image_count) } }); setDraft(null); await load(); } finally { setSaving(false); } };
  return <div className="dance-admin">
    <header className="dance-admin-header"><div><span><Icons.Activity /> Motion control operations</span><h2>Dance Video Console</h2><p>Quản trị catalog chuyển động và toàn bộ đơn làm video thủ công.</p></div><button onClick={() => void load()}><Icons.RefreshCw className={loading ? 'spin' : ''} />Đồng bộ</button></header>
    <section className="dance-admin-kpis"><div><span>Đơn chờ tiếp nhận</span><b>{counts.pending}</b><i className="is-pink" /></div><div><span>Đang xử lý</span><b>{counts.progress}</b><i className="is-cyan" /></div><div><span>Đã hoàn thành</span><b>{counts.complete}</b><i className="is-green" /></div><div><span>Mẫu đang hiển thị</span><b>{templates.filter((item) => item.is_active).length}</b><i className="is-amber" /></div></section>
    <nav className="dance-admin-tabs"><button className={tab === 'orders' ? 'is-active' : ''} onClick={() => setTab('orders')}><Icons.History />Đơn hàng <b>{jobs.length}</b></button><button className={tab === 'templates' ? 'is-active' : ''} onClick={() => setTab('templates')}><Icons.Video />Mẫu video <b>{templates.length}</b></button></nav>
    {tab === 'orders' && <section className="dance-admin-panel"><header><div><h3>Hàng đợi đơn video</h3><p>Tiếp nhận, xử lý và trả video kết quả cho khách.</p></div><label><Icons.Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm mẫu, email, Zalo..." /></label></header><div className="dance-admin-table-wrap"><table><thead><tr><th>Khách & mẫu</th><th>Tham chiếu</th><th>Liên hệ / ghi chú</th><th>Video kết quả</th><th>Trạng thái</th></tr></thead><tbody>{visibleJobs.map((job) => <tr key={job.id}><td><b>{job.dance_video_templates?.title || 'Mẫu đã xóa'}</b><span>{job.users?.display_name || job.users?.email || job.user_id}</span><small>{new Date(job.created_at).toLocaleString('vi-VN')}</small></td><td><div className="dance-admin-images">{(job.character_image_urls || []).map((url: string, index: number) => <a href={url} target="_blank" rel="noreferrer" key={url}><img src={url} alt={`Ảnh ${index + 1}`} /></a>)}</div></td><td><b className="dance-zalo">{job.contact_zalo || 'Không có Zalo'}</b><p>{job.note || 'Không có ghi chú'}</p></td><td><input defaultValue={job.result_video_url || ''} onBlur={(event) => event.target.value !== (job.result_video_url || '') && void updateJob(job, { resultVideoUrl: event.target.value })} placeholder="Dán URL R2" /><label className="dance-admin-upload">Tải video R2<input type="file" accept="video/*" onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadFileToR2(file, `dance-orders/${job.id}/result`).then((url) => updateJob(job, { resultVideoUrl: url })); }} /></label></td><td><select value={job.status} onChange={(event) => void updateJob(job, { status: event.target.value })}><option value="pending">Chờ xử lý</option><option value="accepted">Đã tiếp nhận</option><option value="processing">Đang xử lý</option><option value="completed">Đã hoàn thành</option></select></td></tr>)}{!loading && !visibleJobs.length && <tr><td colSpan={5} className="dance-admin-no-data">Không có đơn hàng phù hợp.</td></tr>}</tbody></table></div></section>}
    {tab === 'templates' && <section className="dance-admin-panel"><header><div><h3>Catalog video mẫu</h3><p>Mỗi mẫu có chi phí và số ảnh nhân vật riêng.</p></div><button className="dance-admin-create" onClick={() => setDraft(freshTemplate(templates.length))}><Icons.Plus />Tạo video mẫu</button></header><div className="dance-admin-template-grid">{templates.map((item) => <article key={item.id}><video src={item.preview_video_url} muted controls preload="metadata" /><div><div className="dance-admin-template-head"><h4>{item.title}</h4><span className={item.is_active ? 'is-live' : ''}>{item.is_active ? 'Đang mở' : 'Đang ẩn'}</span></div><p>{item.description || 'Chưa có mô tả.'}</p><footer><span>{item.price_vcoin} Vcoin · {item.required_image_count} ảnh</span><div><button onClick={() => setDraft(item)} aria-label="Sửa mẫu"><Icons.Edit2 /></button><button onClick={() => { if (window.confirm('Xóa mẫu video này?')) void adminDanceVideoAction({ action: 'delete-template', id: item.id }).then(load); }} aria-label="Xóa mẫu"><Icons.Trash /></button></div></footer></div></article>)}{!loading && !templates.length && <div className="dance-admin-no-templates">Chưa có video mẫu nào.</div>}</div></section>}
    {draft && <aside className="dance-admin-editor"><header><div><span>{draft.id ? 'Chỉnh sửa' : 'Tạo mới'}</span><h3>Mẫu video Motion Control</h3></div><button onClick={() => setDraft(null)}><Icons.X /></button></header><div className="dance-admin-editor-form"><label>Tên mẫu<input value={draft.title || ''} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label><label>Danh mục<input value={draft.category || ''} onChange={(event) => setDraft({ ...draft, category: event.target.value })} /></label><label className="wide">Video URL R2<input value={draft.preview_video_url || ''} onChange={(event) => setDraft({ ...draft, preview_video_url: event.target.value })} placeholder="https://..." /></label><label>Giá Vcoin<input type="number" min="1" value={draft.price_vcoin || ''} onChange={(event) => setDraft({ ...draft, price_vcoin: event.target.value })} /></label><label>Số ảnh cần<input type="number" min="1" max="8" value={draft.required_image_count || 1} onChange={(event) => setDraft({ ...draft, required_image_count: event.target.value })} /></label><label className="wide dance-admin-video-upload">Tải video mẫu lên R2<input type="file" accept="video/*" onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadFileToR2(file, `dance-templates/${draft.id || crypto.randomUUID()}`).then((url) => setDraft({ ...draft, preview_video_url: url })); }} /></label><label className="wide">Mô tả<textarea value={draft.description || ''} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label><label className="wide check"><input type="checkbox" checked={draft.is_active !== false} onChange={(event) => setDraft({ ...draft, is_active: event.target.checked })} />Hiển thị mẫu này cho khách hàng</label></div><footer><button onClick={() => setDraft(null)}>Đóng</button><button disabled={saving || !draft.title || !draft.preview_video_url} onClick={() => void saveTemplate()}>{saving ? 'Đang lưu...' : 'Lưu video mẫu'}</button></footer></aside>}
  </div>;
};
