export const DEFAULT_IMAGE_NEGATIVE_PROMPT = 'crowd, extra people, audience, bystanders, deformed, bad anatomy, disfigured, poorly drawn face, mutation, mutated, extra limb, extra limbs, extra arm, extra arms, extra hand, extra hands, extra leg, extra legs, extra foot, extra feet, duplicated limb, duplicated limbs, duplicate hand, duplicate hands, duplicate foot, duplicate feet, ugly, disgusting, poorly drawn hands, missing limb, floating limbs, disconnected limbs, malformed hands, malformed feet, merged fingers, fused fingers, six fingers, seven fingers, broken wrist, twisted arm, twisted leg, blur, out of focus, long neck, long body, mutated hands and fingers, out of frame, blender, doll, doll face, mannequin face, mannequin body, waxy skin, plastic skin, dark skin, darker skin, tanned skin, bronzed skin, yellow skin, orange skin, oversaturated warm skin, muddy skin tone, incorrect skin tone, skin tone shift, chibi proportions, giant eyes, baby face, stiff pose, rigid pose, stiff limbs, frozen posture, uncanny face, over-smoothed face, cropped, low-res, close-up, poorly-drawn face, out of frame double, two heads, blurred, ugly, disfigured, too many fingers, deformed, repetitive, black and white, grainy, duplicate, photorealistic, realistic photo, sketch, cartoon, drawing, art, 2d';

export const AUDITION_KOREA_MMO_STYLE_PROMPT = [
  'RENDER STYLE DIRECTIVE: Do not send or depend on a style image. Render the final image as a premium Audition Korea MMO 3D game-avatar character, matching the polished visual quality of high-end Korean stylized 3D character art.',
  'Character quality: adult stylized 3D game avatar, elegant tall proportions, normal adult head-to-body ratio, long clean limbs, natural shoulder width, balanced torso and hips, believable hands and feet. Never make the character short, childlike, chibi, baby-faced, doll-like, mannequin-like, or newly invented by AI.',
  'Identity lock: every final subject must come from the uploaded character references only. Preserve exact face identity, hairstyle, hair color, skin tone, body structure, outfit, shoes, accessories, gender presentation, and unique marks from the character slots. Never replace, blend, beautify into a different person, or invent a new character.',
  'Skin and material finish: smooth Korean MMO 3D skin shader with soft subsurface scattering, clean stylized pores, gentle cheek/lip shading, natural specular highlights, refined eye glassiness, detailed eyelashes and eyebrows, no waxy plastic skin, no gritty photoreal skin, no flat cartoon shading.',
  'Body and anatomy: coherent adult anatomy, natural neck length, correct shoulder-to-head placement, elegant but believable posture, stable feet contact, clean fingers, clean wrists, natural limb bends, no elongated neck, no collapsed torso, no broken joints, no oversized head, no tiny body.',
  'Lighting and render: cinematic Unreal/Octane-like 3D render, soft global illumination, high-quality hair strands, fabric texture, jewelry/metal/glass material response, controlled depth of field, crisp face details, vibrant but restrained color grade, premium game-poster finish.',
].join(' ');

export const buildAuditionKoreaMmoStylePrompt = (stylePresetText?: string | null) =>
  [AUDITION_KOREA_MMO_STYLE_PROMPT, stylePresetText ? `Selected style preset keywords: ${stylePresetText}` : '']
    .filter(Boolean)
    .join(' ');
